name: build software
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - software/**
jobs:
  push:
    name: "yolks:${{ matrix.software }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        software:
          - freeradius 
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./software/${{ matrix.software }}
          file: ./software/${{ matrix.software }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/batv45/software:${{ matrix.software }}
